---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dashboard"
subtitle: "Kushan's"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones" Optional icon
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional message
# message:
#   # url: https://....
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   content: "This is a dummy homepage demo. Find more information on github.com/bastienwirtz/homer"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/kushpvo"
    target: "_blank"
  # - name: "Wiki"
  #   icon: "fas fa-book"
  #   url: "https://www.wikipedia.org/"
  #   target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Raspberry Pi"
    icon: "fab fa-raspberry-pi"
    items:
      - name: "RPi Monitor"
        logo: "assets/tools/jenkins.png"
        subtitle: "Monitor Raspberry Pi Stats"
        tag: "RPi-Monitor"
        url: "http://192.168.0.101:8888"
        target: "_blank" # optionnal html a tag target attribute
      - name: "Pi-hole"
        logo: "assets/tools/rabbitmq.png"
        subtitle: "Pi-hole Admin Console"
        tag: "Pi-hole"
        # Optional tagstyle
        # Same styling options as the optional message.
        # tagstyle: "is-success"
        url: "http://192.168.0.101/admin/"
        target: "_blank"
      - name: "Syncthing"
        logo: "assets/tools/jenkins.png"
        subtitle: "Syncthing Web GUI"
        tag: "syncthing"
        url: "http://192.168.0.101:8384"
        target: "_blank" # optionnal html a tag target attribute
  # - name: "Monitoring"
  #   icon: "fas fa-heartbeat"
  #   items:
  #     - name: "M/Monit"
  #       logo: "assets/tools/monit.png"
  #       subtitle: "Monitor & manage all monit enabled hosts"
  #       tag: "monit"
  #       url: "https://mmonit.com/monit/"
  #     - name: "Grafana"
  #       logo: "assets/tools/grafana.png"
  #       subtitle: "Metric analytics & dashboards"
  #       url: "https://grafana.com/"
  #     - name: "Kibana"
  #       logo: "assets/tools/elastic.png"
  #       subtitle: "Explore & visualize logs"
  #       tag: "elk"
  #       url: "https://www.elastic.co/products/kibana"
  #     - name: "Website monitoring"
  #       logo: "assets/tools/pingdom.png"
  #       subtitle: "Pingdom public reports overview"
  #       tag: "CI"
  #       url: "https://www.pingdom.com/"
